### ISSUE TITLE
BIPM feedback on MEP Metre

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#51]
Location | Issue
-- | --
Titlepage | wrong date: should be 20 May 2019
3 | wrong date: should be 20 May 2019
5 | reference to SI brochure shall be a number
5 | text of definition not easily distinguisable from surrounding text: bold font
6 | duplication of page 5, delete
7 | paragraph below equation 1: l in italics
  | replace "clause" by "section" throughout the document
  | Note: µ not in italics (2 x)
8 | legend of Figure 1 not clearly separated from rest of text
9 | equatio 4: insert a space between A and cos
9 | paragraph below equaiton 4: replace ω by φ , replace k by ω
  | paragraph below equation 5: replace appendix by annex, throughout the document
  | legend of Figure 2 not clearly separated from rest of text
10 | 2nd line: replace comma by dot in 0.001
  | error in equation 7: Pi shall be below the horizontal line
  | error in equation 8: t missing
  | last paragraph: replace references to "BIPM standard-frequencies" by numbers
11 | 2nd paragraph: replace comma by dot in 101.325 and 0.27
  | Review layout of table 1: columns are at wrong places, replace decimal commas by dots, exponents need to be superscripts
12 | 3rd paragraph: replace all decimal commas by dots
  | 3rd paragraph: wrong numerical value in 5th line: 0.000 003 2
  | Review layout of table 2;: columns are at wrong places, replace decimal commas by dots, wrong titles
13 | 1st paragraph: cm not in italics
  | Table 3: replace all decimal commas by dots, increase column widts so that no overlap between numbers. The right margin of the document seems to be too large and limits the available space
14 | 2nd paragraph from bottom: replace decimal comma by dot
  | last paragraph:  µ not in italics
16 | reference 1 not correct
18 | equation 1.2, second line: replace 'I2 + I2' with  'I1 + I2'
  | paragraph below equaiton 1.2: symbol for phi should be the same as in the equation
20 | Table 2.1; entry for Abbe error: insert space between d and tan Ѳ
  | Table 2.1, entry for cosine error: repalce decimal comma by dot in 1.2
  | Table 2.1: replace all decimal commas by dots
  | Table 2.1, entry for non planar wavefronts: 'one or two nm' in bold font
  | Table 2.1, entry for polarization crosstalk: 'few nm' in bold font
  | Table 2.1, entry for referenc epath stability: '10.7μm' in bold font
  | Table 2.1, entry for secondary modes in lasers: '1.1 %' in bold font
  | Table 2.1: entry for air refractive index: text of column 1 printed in column 2
  | Table 2.1: entry for air refractive index: '0.00027' and 3 x 10-5 in bold font
  | Table 2.1, entry for light frequency: '1.5 x 10-6', '1011' and '10-9' in bold font
22-23 | Numbers of references in first column in square brackets, need not be repeated at end of reference
  | Names of Journals in italics, as in [3], [9]
24 | 2nd paragraph, 5th line: replace references [3, 13] with [5, 6]
25 | 1st paragraph:  replace 10-8 by 10-8
  | Figure 3.1: insert vertical space between figure caption and text
26 | 2nd paragraph: replace decimal comma by dot in 2.57
26-27 | see comments in lines 45 and 46
29-30 | seec ommnets in lines 45 and 46
31 | 1st paragraph: Si not in italics (2 x)
31 | 3rd paragraph: replace decimal comma with dot
  | 3rd paragraph: group decimals in groups of three
  | 3rd paragraph: several zeros missing in 0.000 003 2
  | paragraph following equation: replace comma with dot, zero missing in 543.102 0504
32 | 3rd paragraph of "Measurement range and conditions": R, S, x, y in italics
  | 4th paragraph: x,y,z in italics
33 | Reference 2 completely wrong

@metanorma/editors if there are non-content issues, please ping @Intelligent2013 or @opoudjis . Thanks!

Original comments file:
[observations mep metre.xlsx](https://github.com/metanorma/bipm-si-brochure/files/5548080/observations.mep.metre.xlsx)

**Comment by manuel489** [comment]
Generated PDF reviewed by BIPM: [mep-metre-definition-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5554279/mep-metre-definition-en.presentation.pdf)

**Comment by anermina** [comment]
Markup fixes are made in #55 .

Note: I also made some markup fixes which weren't on this list.

Pinging @opoudjis for the following:
> Location	Issue
> 7	replace "clause" by "section" throughout the document
>  	Note: µ not in italics (2 x)
> 10	2nd line: replace comma by dot in 0.001
> 11	2nd paragraph: replace comma by dot in 101.325 and 0.27
> 12	3rd paragraph: replace all decimal commas by dots
> 14	2nd paragraph from bottom: replace decimal comma by dot
>  	last paragraph:  µ not in italics
> 20	Table 2.1, entry for cosine error: repalce decimal comma by dot in 1.2
>  	Table 2.1: replace all decimal commas by dots
> 22-23	Numbers of references in first column in square brackets, need not be repeated at end of reference
> 26	2nd paragraph: replace decimal comma by dot in 2.57
> 31	3rd paragraph: replace decimal comma with dot
>  	3rd paragraph: group decimals in groups of three
>  	paragraph following equation: replace comma with dot, zero missing in 543.102 0504
> 33	Reference 2 completely wrong ---> This is actually properly fetched, it's just that it's not displayed in the same format as in BIPM original document.

There is some bug with truncating zeros when there is a larger number of them (or this has been fixed in the meanwhile in .adoc, but I doubt):
> 12	3rd paragraph: wrong numerical value in 5th line: 0.000 003 2
>  	3rd paragraph: several zeros missing in 0.000 003 2


Pinging @Intelligent2013 for the following:
> Location	Issue
> 12	Table 3: replace all decimal commas by dots, increase column widts so that no overlap between numbers. The right margin of the document seems to be too large and limits the available space  ---> I broke `stem` expressions in order to enable wrapping to multiple rows in case we have some limitation for the requested adjustment.
> 8	legend of Figure 1 not clearly separated from rest of text
> 9	legend of Figure 2 not clearly separated from rest of text
>  	Figure 3.1: insert vertical space between figure caption and text

Additional question:
Why is `phi` rendered as `varphi` and vice versa?

In AsciiMath we have this: 
![image](https://user-images.githubusercontent.com/55683568/99459002-b7de5300-292d-11eb-9ddb-e8f7eec2fae9.png)
while it is opposite in generated PDF.

@ronaldtse, there is an error in the original BIPM document:
"See Table 1 and [3.8] to [3.11]" ---> Original document doesn't contain [3.11] reference. Therefore, only [3.8] was properly cross-referenced.

And this was apparently solved in the meanwhile:
> 6	duplication of page 5, delete

**Comment by opoudjis** [comment]
Are BIPM seriously going to use decimal commas in the Brochure, and decimal points in the MEPs?!

As I am constantly obligated to say: Metanorma does not exist in order to perpetuate inconsistency and incoherence. Either all English language text from BIPMM uses decimal points, or none does.

**Comment by Intelligent2013** [comment]
> 7 Note: µ not in italics (2 x)

Source xml:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mi>μ</mi>
	<mtext>m</mtext>
</math>
```

Regarding https://www.w3.org/TR/MathML2/chapter3.html#presm.mi:

```
The default mathvariant and fontstyle would (typically) be "normal" (non-slanted) unless the content is a single character, in which case it would be "italic".
```

If we need to redefine standard behaviour, I can do it via xslt, but I need clear rules for styles.

> 8 legend of Figure 1 not clearly separated from rest of text
> 9 legend of Figure 2 not clearly separated from rest of text
>  Figure 3.1: insert vertical space between figure caption and text

Fixed. Increased vertical space after figure title.


> 12 Table 3: ... increase column widts so that no overlap between numbers. The right margin of the document seems to be too large and limits the available space

I can't increase column widths. They calculated automatically for all flavors.
The right margin fo the document intended for side notes.

>  14 last paragraph:  µ not in italics

see my first comment for `>7 Note: µ not in italics (2 x)`.

**Comment by opoudjis** [comment]
> Pinging @opoudjis for the following:

> Location Issue
> 7 replace "clause" by "section" throughout the document

Was already fixed in https://github.com/metanorma/bipm-si-brochure/issues/40

> 10 2nd line: replace comma by dot in 0.001
> 11 2nd paragraph: replace comma by dot in 101.325 and 0.27
> 12 3rd paragraph: replace all decimal commas by dots
> 14 2nd paragraph from bottom: replace decimal comma by dot
> 20 Table 2.1, entry for cosine error: repalce decimal comma by dot in 1.2
>  Table 2.1: replace all decimal commas by dots
> 26 2nd paragraph: replace decimal comma by dot in 2.57
> 31 3rd paragraph: replace decimal comma with dot
> 3rd paragraph: group decimals in groups of three
>  paragraph following equation: replace comma with dot, zero missing in 543.102 0504

Addressed in https://github.com/metanorma/metanorma-bipm/issues/70

> 22-23 Numbers of references in first column in square brackets, need not be repeated at end of reference

@Intelligent2013 : this is a PDF generation issue (docidentifier not to be appended to reference if of type "metanorma" (i.e. incremental number)

> 33 Reference 2 completely wrong ---> This is actually properly fetched, it's just that it's not displayed in the same format as in BIPM original document.

@Intelligent2013 : this is also a PDF generation issue: If a reference is in normal relaton format, with title rather than formattedref, render it as "{Identifier} {title}" (done for HTML in https://github.com/metanorma/metanorma-bipm/pull/73/commits/0e5d1b312acf4edd7cae64792795572c0ca6b9e1)

> There is some bug with truncating zeros when there is a larger number of them (or this has been fixed in the meanwhile in .adoc, but I doubt):
> 12 3rd paragraph: wrong numerical value in 5th line: 0.000 003 2
>  3rd paragraph: several zeros missing in 0.000 003 2

Yes, isodoc is truncating the decimal when trying to render it.

**Comment by ronaldtse** [comment]
> Yes, twitter_cldr is truncating the decimal when trying to render it. Fixed by imposing precision.

Seems that we need to have a separate gem for rendering numbers. The expectations of twitter_cldr seem too different.

> If a reference is in normal relaton format, with title rather than formattedref, render it as "{Identifier} {title}" (done for HTML in metanorma/metanorma-bipm@0e5d1b3)

And there seems to be a need for proper bibliography text generation at the presentation level? I'm not convinced that the PDF renderer needs to have so much business logic.

**Comment by opoudjis** [comment]
>> Yes, twitter_cldr is truncating the decimal when trying to render it. Fixed by imposing precision.
> Seems that we need to have a separate gem for rendering numbers. The expectations of twitter_cldr seem too different

We may yet do so. We don't need to do so yet: setting precision on a floating point number turned out to be a one-liner.

> And there seems to be a need for proper bibliography text generation at the presentation level? I'm not convinced that the PDF renderer needs to have so much business logic.

Significant refactor, and _I'm not the one constantly adding to backlog so I can't get it it_: https://github.com/metanorma/metanorma-nist/issues/242 has been raised.

**Comment by opoudjis** [comment]
@Intelligent2013 Re μm: this is part of the general issue with keeping units in upright font. This is a source markup issue, and we have just had the asciimath gem allow us to set upright font in asciimath, as our short term solution. (The long term solution is units-specific markup.)

**Comment by manuel489** [comment]
Based on latest PDF release: [mep-metre-definition-en.pdf](https://github.com/metanorma/bipm-si-brochure/files/5653406/mep-metre-definition-en.pdf)

***Remaining issues:***

Location | Comment | Issue
-- | -- | --
13  | Table 3: replace all decimal commas by dots, increase column widts so that no overlap between numbers. The right margin of the document seems to be too large and limits the available space | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59 (hopefully)
16 | reference 1 not correct | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59
22-23 | Numbers of references in first column in square brackets, need not be repeated at end of reference | not fixed
26-27 | Numbers of references in first column in square brackets, need not be repeated at end of reference | not fixed
29-30 | Numbers of references in first column in square brackets, need not be repeated at end of reference | not fixed
33 | Reference 2 completely wrong | not fixed


***Additional issues that weren't before:***
* In page 5, bold paragraph, there is a bad render in the number of light velocity
![Capture1](https://user-images.githubusercontent.com/33627611/101366762-bb556200-387b-11eb-8ded-788d640ec4ab.PNG)
* Problem with reference numbers in Annex 3.
![Capture2](https://user-images.githubusercontent.com/33627611/101367042-138c6400-387c-11eb-92db-85ae97450d3a.PNG)
* Auto-fetch in reference 2 -- Annex 5, renders badly.
![Capture3](https://user-images.githubusercontent.com/33627611/101367232-51898800-387c-11eb-9a9b-bb981a36df27.PNG)

Ping @opoudjis

**Comment by Intelligent2013** [comment]
> In page 5, bold paragraph, there is a bad render in the number of light velocity

There are characters `202F` (Narrow No-Break Space' between numbers. Looks like in the 'Arial Bold' font on MacOs there isn't such character.
In the source xml there isn't nested `<math` tag:
```xml
<stem type="MathML">299 792 458</stem>
```
therefore it renders as normal text. Some lines below there is a math `1/299 792 458` that renders as math svg with font `STIX Two Math` that contains 202F.

I see two possible solutions:
- encode as math (with nested maths inside stem in xml)
- replace `202F` to `A0` (non-break space).

**Comment by opoudjis** [comment]
stem should not be occurring without a math tag inside; will check markup and code.

**Comment by opoudjis** [comment]
"Numbers of references in first column in square brackets, need not be repeated at end of reference": just reported as https://github.com/metanorma/bipm-si-brochure/issues/52 for @Intelligent2013

**Comment by opoudjis** [comment]
33: Still not addressed, PDF issue.  That includes the new reference. These are currently being rendered as raw relaton XML.

> @Intelligent2013 : this is also a PDF generation issue: If a reference is in normal relaton format, with title rather than formattedref, render it as "{Identifier} {title}" (done for HTML in metanorma/metanorma-bipm@0e5d1b3)

In fact at least here, the citation has more information:

<img width="965" alt="Στιγμιότυπο 2020-12-08, 19 54 50" src="https://user-images.githubusercontent.com/1911039/101461659-5428d200-398f-11eb-9138-2a0575b92ffd.png">

The source data is:

````
<bibitem id="iso5436-1" type="standard">  <fetched>2020-12-01</fetched>  <title type="title-intro" format="text/plain" language="en" script="Latn">Geometrical Product Specifications (GPS)</title>  <title type="title-main" format="text/plain" language="en" script="Latn">Surface texture: Profile method; Measurement standards</title>  <title type="title-part" format="text/plain" language="en" script="Latn">Part 1: Material measures</title>  <title type="main" format="text/plain" language="en" script="Latn">Geometrical Product Specifications (GPS) — Surface texture: Profile method; Measurement standards — Part 1: Material measures</title>  <uri type="src">https://www.iso.org/standard/21978.html</uri>  <uri type="obp">https://www.iso.org/obp/ui/#!iso:std:21978:en</uri>  <uri type="rss">https://www.iso.org/contents/data/standard/02/19/21978.detail.rss</uri>  <docidentifier type="ISO">ISO 5436-1</docidentifier>  <docidentifier type="URN">urn:iso:std:iso:5436:-1:stage-90.93:ed-1:en</docidentifier>  <docnumber>5436</docnumber>  <contributor>    <role type="publisher"/>    <organization>      <name>International Organization for Standardization</name>      <abbreviation>ISO</abbreviation>      <uri>www.iso.org</uri>    </organization>  </contributor>  <edition>1</edition>  <language>en</language>  <script>Latn</script>  <status>    <stage>90</stage>    <substage>93</substage>  </status>  <copyright>    <from>2000</from>    <owner>      <organization>        <name>ISO</name>      </organization>    </owner>  </copyright>  <relation type="obsoletes">    <bibitem type="standard">      <formattedref format="text/plain">ISO 5436:1985</formattedref>    </bibitem>  </relation>  <relation type="instance">    <bibitem type="standard">      <fetched>2020-12-01</fetched>      <title type="title-intro" format="text/plain" language="en" script="Latn">Geometrical Product Specifications (GPS)</title>      <title type="title-main" format="text/plain" language="en" script="Latn">Surface texture: Profile method; Measurement standards</title>      <title type="title-part" format="text/plain" language="en" script="Latn">Part 1: Material measures</title>      <title type="main" format="text/plain" language="en" script="Latn">Geometrical Product Specifications (GPS) — Surface texture: Profile method; Measurement standards — Part 1: Material measures</title>      <uri type="src">https://www.iso.org/standard/21978.html</uri>      <uri type="obp">https://www.iso.org/obp/ui/#!iso:std:21978:en</uri>      <uri type="rss">https://www.iso.org/contents/data/standard/02/19/21978.detail.rss</uri>      <docidentifier type="ISO">ISO 5436-1:2000</docidentifier>      <docidentifier type="URN">urn:iso:std:iso:5436:-1:stage-90.93:ed-1:en</docidentifier>      <docnumber>5436</docnumber>      <date type="published">        <on>2000-03</on>      </date>      <contributor>        <role type="publisher"/>        <organization>          <name>International Organization for Standardization</name>          <abbreviation>ISO</abbreviation>          <uri>www.iso.org</uri>        </organization>      </contributor>      <edition>1</edition>      <language>en</language>      <script>Latn</script>      <status>        <stage>90</stage>        <substage>93</substage>      </status>      <copyright>        <from>2000</from>        <owner>          <organization>            <name>ISO</name>          </organization>        </owner>      </copyright>      <relation type="obsoletes">        <bibitem type="standard">          <formattedref format="text/plain">ISO 5436:1985</formattedref>        </bibitem>      </relation>      <place>Geneva</place>    </bibitem>  </relation>  <place>Geneva</place></bibitem>
````

Please, if you have a bibitem containing the following fields, print them out in the citation as follows:

> `./docidentifier`, “`./title`”, `./contributor[role/@type = 'publisher']/organization/name`, `./place` (`./date[@type = 'published']`). `./url`

The date will need to be truncated to year level. No, we don't have data saying Switzerland yet, just Geneva. I'm requesting it to be added, to my irritation.

**Comment by opoudjis** [comment]
The missing stem wrapper is a clash of optimisations:

* If a single number appears in text, I am removing the MathML in Presentation XML, because "it's just a number, it doesn't need the MathML".
* But of course, the localisation is introducing small spaces which are alien to the default font. It needs not to be rendered in the default font, but in MathML, after all.

I think the "it's just a number, it doesn't need the MathML" simplification is laudable, and the text does look odd if you're constantly jumping between normal font and Math font for simple numbers. It is also bewildering that a font as common as Arial does not have U+202F: yes it's obscure, but it's hardly Glagolitic.

The safest thing to do, I conclude, is to block the style optimisation in BIPM, not block it outside of BIPM, and keep an eye out in case we get similar issues with French documents elsewhere. (The real solution is to avoid fonts that can't deal with good typography, which U+202F represents; recall that Asciidoctor inserts U+2009 around em-dashes.)

Oh. And according to Character Palette, my copy of Arial Bold does contain U+202F. I'm not sure we've exhausted this issue; but I'll just dodge it in BIPM.

**Comment by opoudjis** [comment]
The insane Annex 3 numbers are simply because no distinct numbers have been assigned to references there, and autonumbering isn't happening. Autonumbering isn't happening, it turns out, because metanorma-standoc is assuming there is only one bibliography per document. I'm relaxing that constraint.

Note, as we have already discussed, that the reference numbering in the source document is alphanumeric: A4.1, etc. There is actually no reason why you can't use that instead of the numbers in the bibliography: `* [[[dixson,(A4.1)]]]`—the alphanumeric code (which must be placed in parentheses) will be respected as a named reference tag (https://www.metanorma.com/author/topics/document-format/bibliography/#named-reference-tags), and has already been used in NIST.

**Comment by Intelligent2013** [comment]
>  33 | Reference 2 completely wrong


BIPM xslt updated.
![изображение](https://user-images.githubusercontent.com/5559926/101487149-cd63fd00-396e-11eb-8cf9-45a0cff9b973.png)

**Comment by opoudjis** [comment]
We have agreed that the PDF by default will render just ID + Title for relaton bibitems. If more complex rendering is required, I will supply the appropriate formattedRef.

**Comment by opoudjis** [comment]
More complex rendering is not required.

Can I close this?

**Comment by anermina** [comment]
It seems to me that all the initially reported issues have been discussed.
