### ISSUE TITLE
BIPM feedback on MEP Mole

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#52]
Location | Issue
-- | --
5 | first paragraph: replace reference to SI brochure by number, also throught the text
  | text of the definition not clearly distinguished from surrounding text: use bold font
  | definition: replace comma in numerical value by dot
  | definition: group decimals of numerical value by three
  | replace "Clause" by "Section", throughout the document
6 | Equation 3: 28Si
  | 2nd line following equation 3: a(28Si)
  | 2nd paragraph: replace reference to SI brochure by number
  | Equation 4: a(28Si)
7 | paragraph above equation 5: X not in italics
  | paragraph below equation 5: replace decimal comma by dot, group decimals by three
  | pargraph below equation 5: numerical value is wrong: 1.660 539 067 (1) x 10-27
  | the second term of equation 6 is wrong, the (X) at the right belongs to ma below the horizontal line
11 | 1st paragraph: M(12C)
  | paragraph following equation 11: u not in italics (2 x)
  | equation 12: m(12C)
  | paragraph following equaiton 13: Ar€, A in italics
  | last paragraph: reaplace decimal comma by dot
12 | reference 5: space missing in Bartl G and Borys  M
  | the numbering of the references should be in the form of [n], in the first column, not at the end

@metanorma/editors if there are non-content issues, please ping @Intelligent2013 or @opoudjis . Thanks!

Original comments file:
[Observations mep mole.xlsx](https://github.com/metanorma/bipm-si-brochure/files/5548088/Observations.mep.mole.xlsx)

**Comment by manuel489** [comment]
Generated PDF reviewed by BIPM: [mep-mole-definition-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5554273/mep-mole-definition-en.presentation.pdf)

**Comment by anermina** [comment]
Markup fixes are applied in #55 . 



Pinging @opoudjis for:

> Location	Issue
> 5	definition: replace comma in numerical value by dot
>  	definition: group decimals of numerical value by three
>  	replace "Clause" by "Section", throughout the document
> 7	paragraph below equation 5: replace decimal comma by dot, group decimals by three
> 11	last paragraph: reaplace decimal comma by dot
> 12	reference 5: space missing in Bartl G and Borys  M
>  	the numbering of the references should be in the form of [n], in the first column, not at the end

Pinging @Intelligent2013 for the following:
> Location	Issue
> 6	Equation 3: 28Si
>  	Equation 4: a(28Si)
>11 equation 12: m(12C)

These were apparently solved in the meanwhile:
> pargraph below equation 5: numerical value is wrong: 1.660 539 067 (1) x 10-27
> 1st paragraph: M(12C)
> paragraph following equation 11: u not in italics (2 x)

**Comment by Intelligent2013** [comment]
> 6 Equation 3: 28Si
>  Equation 4: a(28Si)
> 11 equation 12: m(12C)

Fixed.

**Comment by opoudjis** [comment]
I believe my issues have been resolved; we can confirm on Monday.

**Comment by manuel489** [comment]
Based on latest PDF release:  [mep-mole-definition-en.pdf](https://github.com/metanorma/bipm-si-brochure/files/5653657/mep-mole-definition-en.pdf)

***Remaining issues:***

Location | Comment | Issue
-- | -- | --
12 | the numbering of the references should be in the form of [n], in the first column, not at the end | not fixed

Ping @opoudjis

**Comment by opoudjis** [comment]
PDF issue:

@Intelligent2013, `docidentifier[@type = 'metanorma']`, e.g. `<docidentifier type="metanorma">[9]</docidentifier>`, is used for numerical identification of references, as in `[1]`. If you are already presenting the references in a numbered list, as is the case here, then those numeric identifiers are redundant, and should not be displayed. (Properly: their number should be what appears in the left margin, rather than any automatic numbering.) Document identifiers of type metanorma are a special class.

There is a task to fully render citations in Presentation XML, https://github.com/metanorma/metanorma-nist/issues/242, which will obviate the need for the PDF to process them separately. That is a breaking change and a significant refactor, and I am not doing it now.

**Comment by Intelligent2013** [comment]
BIPM xslt updated. Now references renders:
![изображение](https://user-images.githubusercontent.com/5559926/101468456-7cdfa600-3954-11eb-9a5b-19eb81030a1b.png)

**Comment by anermina** [comment]
Having this fixed, I believe there are no issues left in this thread. Closing.
