### ISSUE TITLE
BIPM feedback on MEP Kelvin

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#53]
Location | Issue
-- | --
Titlepage | wrong date at bottom: 20 May 2019
3 | wrong date at bottom: 20 May 2019
4 | the words with hyperlinks are not identified, throughout whole document
5 | definition of the kelvin is not easily distinguishing from surrounding text: bold font
  | definition of the kelvin: wrong numerical value: 1.380 649 x 10-23
  | replace decimal comma by dot
  | group decimals by three
  | paragraph below definition: wrong numerical value, replace comma by dot, group by three, see above
  | paragraph below definition: T in italics
  | 3rd paragraph below definition: replace comma with dot in 273.15
  | 4th paragraph below definition: replace comma with dot in 273.16 and in 3.7 and 0.1
  | 5th paragraph below definition: µ not in italics
  | 6th paragraph: replace clause by section, throughout the document
6 | 1st paragraph: could we have 1 and 2 instead of a and b, as in the list just below
  | list item 3: replace comma by dot in 0.9
10 | 1st line: replace comma by dot in  0.1
  | 2nd paragraph below list: wrong name of the document "Relative primary radiometric thermometry"
11 | 2nd line:  replace comma by dot in  0.1
  | equation 4: p missing in equation
  | 3rd paragraph: replace comma by dot in 0.52
  | wrong numerical value for Aµ: -0.000 0079
  | error in equation 5: p is a parameter of C: C(p)
  | paragraph below equation 5: replace A# by Aε
12 | 1st paragraph of 4.3.3: replace fm(p) by fm(p)
  | 1. paragraphh of 4.3.3, 3rd line: m in italics
  | 1st paragraph of 4.3.3: replace fm(0) by fm(0)
15 | 3rd paragraph: replace comma by dot in 0.65 and 0.9
  | 1st paragraph of 5.1: replace comma in 0.5 and 0.65 by dot
  | last paragraph: T in italics (2 x)
  | last paragraph: reference to "Estimates of the differences T-T90" not correct
16 | 1st paragraph: replace comma by dot in 0.65 (2 x) and in 0.9
18 | Bibliography, reference 2: h, e, k and NA in italics

@metanorma/editors if there are non-content issues, please ping @Intelligent2013 or @opoudjis . Thanks!

Original comment file if the math units are unclear here:
[Observations mep kelvin.xlsx](https://github.com/metanorma/bipm-si-brochure/files/5548096/Observations.mep.kelvin.xlsx)

**Comment by manuel489** [comment]
Working on this one...

**Comment by manuel489** [comment]
Generated PDF reviewed by BIPM:  [mep-kelvin-definition-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5554267/mep-kelvin-definition-en.presentation.pdf)

**Comment by manuel489** [comment]
All markup-related issues are fixed in https://github.com/metanorma/bipm-si-brochure/pull/55

Except the ones that are not markup related:

Location | Issue
-- | --
4 | the words with hyperlinks are not identified, throughout whole document
5 | definition of the kelvin is not easily distinguishing from surrounding text: bold font
  | 5th paragraph below definition: µ not in italics 
  | 6th paragraph: replace clause by section, throughout the document 
6 | 1st paragraph: could we have 1 and 2 instead of a and b, as in the list just below 

Ping @Intelligent2013

**Comment by manuel489** [comment]
> 6 | 1st paragraph: could we have 1 and 2 instead of a and b, as in the list just below

@opoudjis , I believe this one is your area? I have opened a ticket in https://github.com/metanorma/metanorma-bipm/issues/68

**Comment by Intelligent2013** [comment]
> 4 | the words with hyperlinks are not identified, throughout whole document

Fixed.


> 5 | definition of the kelvin is not easily distinguishing from surrounding text: bold font

It isn't xslt issue. Definition of the kelvin In adoc  should be marked as bold.

> 5th paragraph below definition: µ not in italics

See 1st comment here: https://github.com/metanorma/bipm-si-brochure/issues/51#issuecomment-729552401

> 6th paragraph: replace clause by section, throughout the document

It isn't xslt issue. ping @opoudjis 

> 6 | 1st paragraph: could we have 1 and 2 instead of a and b, as in the list just below

Source XML issue.
```xml
<p id="_295059f4-4697-4810-9f27-1c841b5d2cde">The purpose of this section is to clarify the terms that will be used in the following sections on <xref target="item-1">a)</xref> primary thermometry and <xref target="item-2">b)</xref> defined temperature scales. A clear and well-defined nomenclature is essential to support an unambiguous taxonomy of methods in the <em>MeP</em>-K. The <em>MeP</em>-K uses the following definitions.</p>
			<ol id="_2569779b-901d-48ac-b3d6-7a2b2bb137dd" type="arabic" start="">
				<li id="item-1">
					<p id="_9dd6a78f-5505-4ef5-b972-fe1f6a67b546">
						<em>Primary thermometry</em>
```
ping @opoudjis

**Comment by opoudjis** [comment]
> 6 | 1st paragraph: could we have 1 and 2 instead of a and b, as in the list just below

https://github.com/metanorma/metanorma-bipm/issues/68 has been resolved.

> 6th paragraph: replace clause by section, throughout the document

Has also been resolved in #40

There's a few moving parts still ongoing, but I propose to do release Monday, and will regenerate all docs for re-review then.

**Comment by manuel489** [comment]
Based on latest PDF release: [mep-kelvin-definition-en.pdf](https://github.com/metanorma/bipm-si-brochure/files/5653849/mep-kelvin-definition-en.pdf)

***Remaining issues:***

Location | Comment | Issue
-- | -- | --
5 | definition of the kelvin is not easily distinguishing from surrounding text: bold font | not fixed

Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
>  5 | definition of the kelvin is not easily distinguishing from surrounding text: bold font

In source .adoc it marks as quote without bold:
```adoc
== Definition of the kelvin

The definition of the kelvin, SI base unit of temperature, is as follows <<bipm>>:

____
The kelvin, symbol K, is the SI unit of thermodynamic temperature. It is defined by taking the fixed numerical value of the Boltzmann constant stem:[k] to be stem:[1.380649 xx 10^{-23}] when expressed in the unit stem:["J K"^{-1}], which is equal to stem:["kg m"^2 "s"^{-2} "K"^{-1}], where the kilogram, metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta nu_{"Cs"}].
____
```

Add `*` around text.

**Comment by opoudjis** [comment]
> Add `*` around text.

We have established that boldface MathML simply doesn't work, but yeah, they can try that.

**Comment by manuel489** [comment]
Done. Thanks!
No issues in this thread.

**Comment by anermina** [comment]
Since no issues left, closing.
